# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Code quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      if: always()
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_development.txt
        pip install -r requirements.txt
    - name: Lint with pylint
      if: always()
      run: |
        pylint openweathermap_exporter
    - name: Check types with mypy
      if: always()
      run: |
        mypy --install-types --non-interactive --ignore-missing-imports openweathermap_exporter
#    - name: Test with unittest
#      run: |
#        python3 -m unittest openweathermap-exporter
